import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#006242',
        'on-error': '#ffffff',
        'surface-container': '#f1ecf2',
        'inverse-on-surface': '#f7f2f8',
        'surface-tint': '#673ab6',
        background: '#faf8ff',
        primary: '#673ab6',
        'on-secondary-fixed': '#1d192b',
        secondary: '#625b71',
        'tertiary-fixed': '#6ffbbe',
        surface: '#faf8ff',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e7e0eb',
        'inverse-primary': '#d0bcff',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f7f2f8',
        'on-surface-variant': '#49454f',
        'tertiary-fixed-dim': '#4edea3',
        'tertiary-container': '#007d55',
        'surface-variant': '#e7e0eb',
        'on-surface': '#1c1b1f',
        'secondary-fixed': '#e8def8',
        'on-secondary-container': '#1d192b',
        outline: '#79747e',
        error: '#ba1a1a',
        'primary-fixed-dim': '#d0bcff',
        'on-secondary': '#ffffff',
        'on-background': '#1c1b1f',
        'secondary-fixed-dim': '#ccc2dc',
        'primary-fixed': '#ebddff',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-container': '#bdffdb',
        'on-primary-fixed-variant': '#4f1c9d',
        'surface-bright': '#faf8ff',
        'on-tertiary-fixed-variant': '#005236',
        'error-container': '#ffdad6',
        'inverse-surface': '#313033',
        'surface-container-high': '#ece6f0',
        'surface-dim': '#ded8e1',
        'outline-variant': '#ccc3d5',
        'secondary-container': '#e8def8',
        'on-secondary-fixed-variant': '#4a4458',
        'on-primary-fixed': '#21005d',
        'on-primary-container': '#21005d',
        'primary-container': '#ebddff',
        'on-error-container': '#410002',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
